"""Render helpers for MCP read handlers.

Ported from cli/src/daemon/tools.rs — `render_claude_md` and `render_handover`.
Section structure matches the Rust originals; output is not byte-perfect but
is semantically equivalent.
"""
from __future__ import annotations

from datetime import datetime, timezone
from typing import Any


def _str(obj: dict[str, Any], key: str, default: str = "") -> str:
    v = obj.get(key)
    return v if isinstance(v, str) and v else default


def _arr_of_str(obj: dict[str, Any], key: str) -> list[str]:
    v = obj.get(key)
    if not isinstance(v, list):
        return []
    return [s for s in v if isinstance(s, str)]


def render_claude_md(full: dict[str, Any]) -> str:
    """Generate a CLAUDE.md-ready markdown brief from a project aggregate dict."""
    name = _str(full, "name", "Project")
    pitch = _str(full, "pitch", "(no pitch yet)")

    # Stack items
    stack_items: list[str] = []
    for s in full.get("stack") or []:
        if not isinstance(s, dict):
            continue
        n = _str(s, "name")
        k = _str(s, "kind")
        if not n:
            continue
        stack_items.append(f"{n} ({k})" if k else n)

    # Infra
    infra = full.get("infra") or {}
    if not isinstance(infra, dict):
        infra = {}

    # Context
    ctx = full.get("context") or {}
    if not isinstance(ctx, dict):
        ctx = {}
    current_focus = _str(ctx, "current_focus", "(unset)")
    next_step = _str(ctx, "next_step", "(unset)")
    user_wants = _str(ctx, "user_wants", "(unset)")
    blocked_by = _str(ctx, "blocked_by", "(none)")
    open_questions = _arr_of_str(ctx, "open_questions")

    # Links
    link_lines: list[str] = []
    for lnk in full.get("links") or []:
        if not isinstance(lnk, dict):
            continue
        kind = _str(lnk, "kind", "link")
        label = _str(lnk, "label")
        url = _str(lnk, "url")
        if not url:
            continue
        label_display = label if label else kind
        link_lines.append(f"- [{kind}] {label_display} — {url}")

    # Commands
    cmd_lines: list[str] = []
    for c in full.get("commands") or []:
        if not isinstance(c, dict):
            continue
        lbl = _str(c, "label")
        cmd = _str(c, "command")
        if not lbl or not cmd:
            continue
        cmd_lines.append(f"- {lbl}: `{cmd}`")

    # Assemble
    md: list[str] = []
    md.append(f"# {name}\n")
    md.append(f"\n{pitch}\n")
    md.append("\n## Stack\n")
    if stack_items:
        for item in stack_items:
            md.append(f"- {item}\n")
    else:
        md.append("- (no stack items recorded)\n")

    md.append("\n## Infra\n")
    any_infra = False
    for field, label in [
        ("server_alias", "Server"),
        ("domain_primary", "Domain"),
        ("db_host", "DB"),
        ("dns_provider", "DNS"),
    ]:
        val = _str(infra, field)
        if val:
            md.append(f"- {label}: {val}\n")
            any_infra = True
    if not any_infra:
        md.append("- (no infra recorded)\n")
    md.append("- Secrets: see `hangar secret list`\n")

    md.append("\n## Current state\n")
    md.append(f"- Focus: {current_focus}\n")
    md.append(f"- Next: {next_step}\n")
    md.append(f"- User wants: {user_wants}\n")
    if open_questions:
        md.append("- Open questions:\n")
        for q in open_questions:
            md.append(f"  - {q}\n")
    else:
        md.append("- Open questions: (none)\n")
    md.append(f"- Blocked by: {blocked_by}\n")

    md.append("\n## Links\n")
    if link_lines:
        for ll in link_lines:
            md.append(f"{ll}\n")
    else:
        md.append("- (no links recorded)\n")

    md.append("\n## Commands\n")
    if cmd_lines:
        for cl in cmd_lines:
            md.append(f"{cl}\n")
    else:
        md.append("- (no commands saved — add one with `hangar set-command`)\n")

    ts = datetime.now(timezone.utc).isoformat()
    md.append(f"\nGenerated by Vibecell 0.1.0 on {ts}.\n")

    return "".join(md)


def render_handover(full: dict[str, Any]) -> str:
    """Generate a prose resurrection/onboarding brief from a project aggregate dict."""
    name = _str(full, "name", "the project")
    pitch = _str(full, "pitch", "(no pitch captured yet)")
    status = _str(full, "status", "idea")

    ctx = full.get("context") or {}
    if not isinstance(ctx, dict):
        ctx = {}
    current_focus = _str(ctx, "current_focus")
    next_step = _str(ctx, "next_step")
    user_wants = _str(ctx, "user_wants")
    blocked_by = _str(ctx, "blocked_by")
    open_q = _arr_of_str(ctx, "open_questions")
    known_issues = _arr_of_str(ctx, "known_issues")

    commands_count = len(full.get("commands") or [])

    parts: list[str] = []
    parts.append(f"{name} — {pitch}.\n\n")

    # Where it stands
    parts.append(f"Status: **{status}**. ")
    if current_focus:
        parts.append(f"Current focus is *{current_focus}*. ")
    else:
        parts.append("No explicit focus is recorded. ")
    if user_wants:
        parts.append(f"The user wants: {user_wants}. ")
    parts.append("\n\n")

    # Known issues
    if known_issues:
        parts.append("Known issues:\n")
        for ki in known_issues:
            parts.append(f"- {ki}\n")
        parts.append("\n")
    else:
        parts.append(
            "No known issues logged. "
            "(Placeholder: SSL / commits / GitHub issues integrations will surface real "
            "breakage once Spec 3 Phase 5 lands.)\n\n"
        )

    # What you were about to do
    if next_step:
        parts.append(f"**What you were about to do:** {next_step}. ")
    else:
        parts.append("**What you were about to do:** not recorded. ")
    if blocked_by and blocked_by != "(none)":
        parts.append(f"(Blocked by: {blocked_by}.) ")
    parts.append("\n\n")

    # Open questions
    if open_q:
        parts.append("Open questions:\n")
        for q in open_q:
            parts.append(f"- {q}\n")
        parts.append("\n")

    # Suggested first move
    parts.append("**Suggested first move:** ")
    if next_step:
        suggestion = f"pick up where you left off — {next_step}"
    elif current_focus:
        suggestion = f"continue current focus ({current_focus})"
    elif commands_count > 0:
        suggestion = (
            "browse saved commands with `hangar run <label>` to recall what this project does, "
            "then call `vibecell.update_context` to set a focus before coding"
        )
    else:
        suggestion = (
            "call `vibecell.update_context` to set current_focus + next_step, "
            "then start a concrete task"
        )
    parts.append(f"{suggestion}.\n")

    return "".join(parts)
